apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-api-k8s
  name: flask-api-k8s-svc
  namespace: lab-server
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 32331
  selector:
    app: flask-api-k8s
  type: NodePort

