apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: lab-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:

      labels:
        app: backend
    spec:
      containers:
      - image: idrisniyi94/api-backend-k8s:stable
        name: api-backend-k8s
        ports:
        - containerPort: 5000
        resources: {}

