apiVersion: v1
kind: Service
metadata:
  # creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: lab-server
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32330
  selector:
    run: nginx
  type: NodePort
# status:
#   loadBalancer: {}
