apiVersion: apps/v1
kind: Deployment
metadata:
  # creationTimestamp: null
  labels:
    app: nginx
  name: nginx
  namespace: lab-server
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      # creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:perl
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
# status: {}
